architecture: Cybertron
bias: false
dropout: 0.0
hidden_dim: 768
max_seq_len: 768
multiple_of: 32
n_heads: 8
n_layers: 12
rope_beta: 10000.0
rope_scaling_factor: 1.0
rope_scaling_type: dynamic
vocab_size: 64793
