dataset_params:
  train_data_path: [
        './data/pretrain_data.bin'
        #'./data/baidubaike_563w.bin',
        #'./data/medical_book.bin',
        # './data/medical_encyclopedia.bin',
        # './data/medical_qa.bin',
        # './data/wiki.bin'
    ]
  valid_data_path: [
        './data/valid_data.bin'
    ]
  sft_data_path: './data/sft_data.csv'
  test_data_path: [
        'data/shibing624-medical-pretrain/pretrain/test_encyclopedia.json',
    ]
  
  sft_long_data_path_train: './data/sft_long_data_train.csv'
  sft_long_data_path_val: './data/sft_long_data_val.csv'
  rw_data_path: './data/hh-rlhf/helpful-base'
  ppo_data_path: './data/ppo_data'

model_path: 'best.model'
merge_lora_to_save: False
merge_lora_on_load: False

train_params:
  use_deepspeed: False
  max_epoch: 2
  log_iters: 200
  save_iters: 2000
  eval_iters: 2000
  eval_only: False
  always_save_ckpt: True
  init_from: 'scratch'
  grad_accum_steps: 64
  batch_size: 4
  learning_rate: 0.0003
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 1000
  lr_decay_iters: 80000
  min_lr: 0.00001
  backend: 'nccl'
  device: 'cuda'
  compile: False
  optimizer_type: 'AdamW' # AdamW/GaLoreAdamW/GaLoreAdamW8bit/GaLoreAdafactor

  
fine_tuning_params:
  ft_type: 'full_ft'  # full_ft/lora/qlora 
  lora_mudule: 'linear'  # linear/embedding/all
  lora_attn_dim: 8
  lora_attn_alpha: 128
  lora_dropout: 0.0
  lora_r_dropout: 0.0

eval_params:
  max_new_tokens: 100
  temperature: 1.0
  top_p: 0.4
  top_k: 30
  seed: 1337
  shot: 0

ppo_params:
  reward_lm_loss_factor: 0.0
  validation_metric: 'loss'
  eps: 0.000001
  num_prefetch: 32
  num_workers: 1
  num_rollouts: 64
  critic_lr: 0.0000015
  reward_clip: 10.
  pg_clip: 0.2
  value_clip: 0.2
  entropy_clip: 35.
  advantage_clip: 0.5
  kl_penalty_weight: 0.02
  vf_loss_weight: 1.
  entropy_loss_weight: 0.
  ppo_pretrain_loss_weight: 0.
  use_reward_clip: True
  use_reward_scaling: True
  use_reward_norm: True
  use_critic_loss_clip: True
  use_policy_loss_clip: True
  use_advantage_norm: True
  use_advantage_clip: True
  use_ppo_pretrain_loss: True
  use_entropy_loss: True